### PR TITLE
Improve Ref Docs

### PR DESCRIPTION
**Pull request by sommersoft**
[Per Issue #566](https://github.com/adafruit/circuitpython/issues/566)

### CODE REVIEW

**Review by kattni — APPROVED** [review]
Looks great thanks!

**Comment by kattni** [comment]
Please resolve the travis build issue before I merge. Thanks!

**Comment by sommersoft** [comment]
Currently fails due to incorrect image link in the README. 

Will update once willingc has had a chance to view this [comment](https://github.com/adafruit/circuitpython/issues/566#issuecomment-368705593) regarding image filepath issues between GitHub and RTD.

**Comment by sommersoft** [comment]
@kattni set the image filepath back to the Travis/Sphinx passing value. Also updated my comment so that even if willingc hasn't seen it yet, it will direct her to the specific commit's version. So we're GTG on this one.

**Comment by kattni** [comment]
Thanks for the update!

**Pull request merged**
